create database spa;

use spa;

CREATE TABLE `spa`.`r1` (
   `PE` char(10) NOT NULL,
   `FY_reported` int(11) NOT NULL,
   `Organization` char(200) DEFAULT NULL,
   `BA` int(11) DEFAULT NULL,
   `BA_Title` char(100) DEFAULT NULL,
   `PE_Title` char(200) DEFAULT NULL,
   `CREATE_DTM` timestamp DEFAULT CURRENT_TIMESTAMP,
   `FY_1996` double DEFAULT NULL,
   `FY_1997` double DEFAULT NULL,
   `FY_1998` double DEFAULT NULL,
   `FY_1999` double DEFAULT NULL,
   `FY_2000` double DEFAULT NULL,
   `FY_2001` double DEFAULT NULL,
   `FY_2002` double DEFAULT NULL,
   `FY_2003` double DEFAULT NULL,
   `FY_2004` double DEFAULT NULL,
   `FY_2005` double DEFAULT NULL,
   `FY_2006` double DEFAULT NULL,
   `FY_2007` double DEFAULT NULL,
   `FY_2008` double DEFAULT NULL,
   `FY_2009` double DEFAULT NULL,
   `FY_2010` double DEFAULT NULL,
   `FY_2011` double DEFAULT NULL,
   `FY_2012` double DEFAULT NULL,
   `FY_2013` double DEFAULT NULL,
   `FY_2014` double DEFAULT NULL,
   `FY_2015` double DEFAULT NULL,
   `FY_2016` double DEFAULT NULL,
   `FY_2017` double DEFAULT NULL,
   UNIQUE KEY `r101` (`PE`,`FY_reported`)
 );
 
 CREATE TABLE `spa`.`r2` (
   `PE`           char(8)   NOT NULL,
   `PE_Title`     char(200) NOT NULL,
   `Budget_Year`  int(11)   NOT NULL,
   `Budget_Cycle` char(5) NOT NULL,
   `Submission_Date` date NOT NULL,
   `Service_Agency_Name` char(200) DEFAULT NULL,
   `Appropriation_Code`  int(11)   NOT NULL,
   `Appropriation_Name` char(200) DEFAULT NULL,
   `BA`           int(11)   DEFAULT NULL,
   `BA_Title`     char(100) DEFAULT NULL,
   `CREATE_DTM`   timestamp DEFAULT CURRENT_TIMESTAMP,
   `FY_2010`      double    DEFAULT NULL,
   `FY_2011`      double    DEFAULT NULL,
   `FY_2012`      double    DEFAULT NULL,
   `FY_2013`      double    DEFAULT NULL,
   `FY_2014`      double    DEFAULT NULL,
   `FY_2015`      double    DEFAULT NULL,
   `FY_2016`      double    DEFAULT NULL,
   `FY_2017`      double    DEFAULT NULL,
   `FY_2018`      double    DEFAULT NULL,
   `FY_2019`      double    DEFAULT NULL,
   `FY_2020`      double    DEFAULT NULL,
   `FY_2021`      double    DEFAULT NULL,
   `FY_2022`      double    DEFAULT NULL,
   `FY_2023`      double    DEFAULT NULL,
   UNIQUE KEY `r101` (`PE`,`Budget_Year`)
 ) ENGINE=InnoDB DEFAULT CHARSET=utf8;